### ISSUE TITLE
Can`t intall fastprofkernel

### ISSUE THREAD

**Issue by phdiassantos** [Rostlab/ProNA2019#2]
Hi there, I`m following your pipeline but when I have to install fastprofkernel i can`t connect to the Debian repository, or download the deb file. Could you help me?

**Comment by T1mK** [comment]
Hello,

You can download our debian package and source code from our public FTP server at ftp://rostlab.org/fastprofkernel/ .

If you're using a newer version of Firefox, it won't automatically open FTP protocol connections any longer. What you'll need to do is use the command line, or another FTP client.

If you're using a terminal, command prompt, or console, you can connect to our FTP server using the `ftp` command as so:

```
ftp -p rostlab.org
```
You then use the user `anonymous` as the username, and your e-mail address as password.

Please refer to your favorite search machine for learning more about the `ftp` command, if not already familiar.

I hope this helps. If not, please re-open this ticket.
